# Generated by Django 2.1 on 2020-06-14 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200614_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_data',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 22, 36, 26, 337871, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 22, 36, 26, 337313, tzinfo=utc)),
        ),
    ]
